### ISSUE TITLE
Broken on MacOS

### ISSUE THREAD

**Issue by IronhandedLayman** [christianrondeau/vim-base64#1]
On the MacOS versions of base64, there is no option `--wrap=0` or `--ignore-garbage` so the plugin won't work on MacOS. `has("unix")` is true there, so it goes down that path. On my version I was able to fix by adding a branch to the `if-elseif-endif` code in `autoload/base64.vim` to check for `has("macunix")` and issue the commands without those switches. I am not sure if that's how you want to handle the issue, but I can issue a pull request if needed. The change passes Vader tests.

**Comment by christianrondeau** [comment]
If you can create a pull request that would be great! Thanks for the find!

**Comment by IronhandedLayman** [comment]
Pull request #2 should address this issue.

**Comment by christianrondeau** [comment]
Merged! Thanks for the contribution :)
