### ISSUE TITLE
Functions are backwards

### ISSUE THREAD

**Issue by ianwitherow** [christianrondeau/vim-base64#3]
`atob` is the one that takes a base64 string and decodes it, and `btoa` takes a string and encodes it to base64.

**Comment by christianrondeau** [comment]
Oops, looks like you're right! I'm traveling now, I'll confirm when I'm back home (tomorrow).

**Comment by christianrondeau** [comment]
This looks all good... Hopefully I won't break any scripts using this, but since it's backward I think I don't really have a choice...

Thanks for the PR!
