### ISSUE TITLE
Indentation breaks on decoding when autoindent is on

### ISSUE THREAD

**Issue by foben** [christianrondeau/vim-base64#5]
I am working with a lot of base64 encoded yaml config files.
I realized that the  indentation of multiline strings is broken after encoding and subsequent decoding,
when the autoindent setting is on: https://asciinema.org/a/gJjLKTYQp7WIW2JRYgUTTvjAM

Is there a possibility to handle this within the plugin, or is there a way for me to fix this in vimrc?

**Comment by christianrondeau** [comment]
I think it's because of the way the text is inserted; it's like if you were typing "enter", and then adding the two spaces, pressing enter again (auto-indent kicks in) and again entering two space.s

Let me check if I can find a quick workaround :)

**Comment by christianrondeau** [comment]
So the workaround (well, the right solution actually) is to set paste mode for the duration of the replacement. Looking into it.

**Comment by christianrondeau** [comment]
Here you go, that should work :) I'll close this issue, let me know if that doesn't work!
