### ISSUE TITLE
usage help

### ISSUE THREAD

**Issue by nrobert13** [christianrondeau/vim-base64#6]
hi,

sorry for this dumb issue, but I don't really understand the usage of this plugin.
using it with vim-plug, installed successfully.
here the steps I try:
1 selecting the base64 string with viw, 
2. hit `:` 
3. I get `:'<,'> `
4. add `btoa` to the end of the line at #3 
5. I get
 ```E492: Not an editor command: '<,'>btoa```

**Comment by christianrondeau** [comment]
No problem :)

After making a selection, the shortcut is <kbd>leader</kbd> followed by `btoa` or `atob`, not <kbd>:</kbd>.

If you are unsure what your leader key is, type `:let mapleader` (if you only see `mapleader` it probably means your leader is "spacebar", if it shows `<Leader>` it means the key is `\`)

Hope that helps, let me know how it goes!

**Comment by nrobert13** [comment]
hey, thanks for quick reply.

so if I type `:let mapleader` I get `Undefined variable: mapleader`, I understand this means it's default, what is `\`, tried to hit `\` after selection is done and type `btoa`, but nothing happens ...
quite confused.

**Comment by christianrondeau** [comment]
Mmmh let's try a few things then.

Try typing `:vmap <leader>btoa` in vim, see the output. It should give you something like `v   <Space>btoa * :<C-U>call base64#v_btoa()<CR>` (where `<Space>` is your leader). If you get `no mapping found` it means you don't actually have the plugin installed. Otherwise it means it _should_ work, or at least throw an error if there's a problem.

If the plugin is installed, try defining a mapleader in your `.vimrc` file, such as `let mapleader = "\<Space>"`

Let me know how it goes!

**Comment by nrobert13** [comment]
here's what I get:
`v  \btoa       * :<C-U>call base64#v_btoa()<CR>` so I assume `\` is my leader and plugin installed ...

tried `let mapleader = "\<Space>"`
and now it works...

out of curiosity, what does `atob` and `btoa` stand for?
I thought it's Ascii-TO-Base64 and vice versa, but the logic is inverted, basically 
`atob` - does Base64-TO-Ascii

I tried to swap them like this:
```
vnoremap <silent> <leader>atob :<c-u>call base64#v_btoa()<cr>
vnoremap <silent> <leader>btoa :<c-u>call base64#v_atob()<cr>
```
but it doesn't work, I still get the original behavior.

**Comment by christianrondeau** [comment]
Uh, that's weird, I don't know if it's a behavior of vim-base64 or not though. You can try playing with things like `:noremap <leader>test :echo "hi!"<cr>` and your mapleader to figure out what's wrong with the default leader (though setting one is probably preferable anyway).

As for the letters, they stand for "bytes to ascii" (data to base64) and "ascii to bytes" (base64 to data). This is what you'll find in APIs such as NodeJS for example: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding - I was confused by this too, but I prefer a predictable and documented name anyway.

Hope that helps!

**Comment by nrobert13** [comment]
thanks for the quick and detailed replies! Awesome plugin!
